import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root = new URL('../', import.meta.url);
await fs.mkdir(new URL('qa/',root), {recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const base='http://127.0.0.1:4173/';
const routes=['index.html','works.html','about.html','expertise.html','playground.html','contact.html','certificate.html','cv.html',...['watchlur','dataexchange','alrizan','myindihome','smartcapex','zeitplan','weddoes','endlesscode','chevalier','mediku'].map(x=>'works/'+x+'/index.html')];
let pagesChecked=0;
for(const width of [1440,390]){
 await page.setViewportSize({width,height:1000});
 for(const route of routes){
  const response=await page.goto(base+route,{waitUntil:'networkidle'});
  assert.equal(response.status(),200,route);
  await page.evaluate(()=>document.fonts.ready);
  const layout=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,h1:document.querySelector('h1').innerText}));
  assert.ok(layout.scroll<=layout.width+1,`${route} overflows at ${width}: ${JSON.stringify(layout)}`);
  assert.ok(layout.h1.trim().length>0,route+' missing heading');
  await page.locator('img').evaluateAll(images=>images.forEach(im=>{im.loading='eager';}));
  await page.waitForFunction(()=>[...document.images].every(i=>i.complete),{timeout:15000});
  const broken=await page.locator('img').evaluateAll(images=>images.filter(i=>!i.naturalWidth).map(i=>i.src));
  assert.deepEqual(broken,[],route+' broken images');
  if(['index.html','works.html','about.html','contact.html','playground.html','works/watchlur/index.html'].includes(route)){
   const name=route.replaceAll('/','-').replace('.html','');
   await page.screenshot({path:new URL(`qa/${name}-${width}.png`,root).pathname.replace(/^\/([A-Za-z]:)/,'$1'),fullPage:true});
   if(route==='index.html')await page.screenshot({path:new URL(`qa/home-viewport-${width}.png`,root).pathname.replace(/^\/([A-Za-z]:)/,'$1')});
  }
  pagesChecked++;
 }
}
await page.setViewportSize({width:1440,height:1000});
await page.goto(base+'works.html');
await page.getByRole('button',{name:'Branding',exact:true}).click();
assert.equal(await page.locator('.work-card:visible').count(),2);
await page.locator('#project-search').fill('not-a-project');
assert.equal(await page.locator('.work-card:visible').count(),0);
assert.equal(await page.locator('.empty-state').isVisible(),true);
await page.getByRole('button',{name:'Reset filters'}).click();
assert.equal(await page.locator('.work-card:visible').count(),10);
await page.locator('#project-search').fill('watchlur');
assert.equal(await page.locator('.work-card:visible').count(),1);
await page.goto(base+'works.html?filter=development');
assert.equal(await page.locator('.work-card:visible').count(),8);
await page.goto(base+'works/watchlur/index.html');
await page.locator('.zoom-image').first().click();
assert.equal(await page.locator('dialog').evaluate(el=>el.open),true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('dialog').evaluate(el=>el.open),false);
assert.equal(await page.locator('.zoom-image').first().evaluate(el=>el===document.activeElement),true);
await page.setViewportSize({width:390,height:844});
await page.goto(base+'index.html');
await page.getByRole('button',{name:'Open navigation'}).click();
assert.equal(await page.locator('#mobile-menu').isVisible(),true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('#mobile-menu').isVisible(),false);
assert.equal(await page.locator('#main').evaluate(el=>el.inert),false);
await page.getByRole('button',{name:'Open navigation'}).click();
await page.locator('#mobile-menu').getByRole('link',{name:/About/}).click();
assert.ok(page.url().endsWith('about.html'));
await page.goto(base+'playground.html');
assert.equal(await page.locator('#art-motion').getAttribute('aria-pressed'),'true');
await page.getByRole('button',{name:'Lavender',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'Lavender',exact:true}).getAttribute('aria-pressed'),'true');
await page.locator('#complexity').fill('60');
assert.equal(await page.locator('#complexity-value').textContent(),'60');
await page.locator('#art-reset').click();
assert.equal(await page.locator('#complexity').inputValue(),'36');
await page.locator('#type-input').fill('Made with care');
assert.equal(await page.locator('#type-preview').textContent(),'Made with care');
await page.locator('#type-toggle').click();
assert.equal(await page.locator('#type-toggle').getAttribute('aria-pressed'),'true');
const downloadPromise=page.waitForEvent('download');
await page.locator('#art-save').click();
const download=await downloadPromise;
assert.equal(download.suggestedFilename(),'danis-order-and-chaos.png');
await page.goto(base+'contact.html');
await page.locator('[name=name]').fill('Portfolio QA');
await page.locator('[name=email]').fill('qa@example.com');
await page.locator('[name=message]').fill('I would like to discuss a thoughtful new website.');
await page.locator('[name=service]').first().check();
// Keep the test from opening a native mail application while verifying the exact draft link.
await page.locator('#open-draft').evaluate(a=>a.addEventListener('click',event=>event.preventDefault()));
await page.getByRole('button',{name:'Prepare email draft'}).click();
assert.equal(await page.locator('#brief-result').isVisible(),true);
assert.match(await page.locator('#brief-preview').inputValue(),/UI \/ UX design/);
assert.match(await page.locator('#open-draft').getAttribute('href'),/^mailto:daniszaidan@gmail.com\?subject=/);
assert.deepEqual(errors,[],'Runtime errors');
console.log(`PASS: ${pagesChecked} page/viewport checks, no overflow or broken images; filters, search, query filters, gallery, focus restoration, mobile navigation, reduced motion, playground controls, PNG export and email draft.`);
await fs.writeFile(new URL('qa/results.json',root),JSON.stringify({pagesChecked,viewports:[1440,390],runtimeErrors:errors,result:'pass',date:new Date().toISOString()},null,2));
await browser.close();
